### ISSUE TITLE
Eucaconsole WebOb version conflict Eucalyptus 4.4.4

### ISSUE THREAD

**Issue by ndtroubleshoot** [Corymbia/eucalyptus#124]
On out of the box Centos 7.5 Minimal Install.  Fully Updated.  Eucaconsole appears to be looking for a newer version of WebOb (1.3.1) that is not supplied by the mainstream CentOS or Euca repos during install.
From /var/log/eucaconsole_startup.log:

```
Traceback (most recent call last):
  File "/bin/eucaconsole", line 106, in <module>
    daemonize(start_console)
  File "/bin/eucaconsole", line 61, in daemonize
    func()
  File "/bin/eucaconsole", line 73, in start_console
    load_entry_point('pyramid', 'console_scripts', 'pserve')(args)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2259, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2272, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (WebOb 1.2.3 (/usr/lib/python2.7/site-packages), Requirement.parse('WebOb>=1.3.1'))
```

**Comment by sjones4** [comment]
The required `python-webob1.4` dependency is from epel:

`yum install epel-release`

If you have an older version installed then you should remove it, e.g.:

`yum remove python-webob`

If this does not address your issue then please provide more details to allow the failure to be reproduced.
