### ISSUE TITLE
AWSCLI tool documentation unclear / not working

### ISSUE THREAD

**Issue by lesparker** [Corymbia/eucalyptus#193]
The awscli commands don't seem to work against Eucalyptus 5.0

I have follower\d the directions in the blog for 5.0, and get the following:

**aws ec2 describe-regions** 

An error occurred (404 Not Found) when calling the DescribeRegions operation: unknown

--------------------------
The contents of my config file are:

**cat .aws/config** 

[plugins]
eucalyptus = awscli_plugin_eucalyptus

[default]
#ufshost = euca-10-10-10-10.euca.me
#ufshost = localhost.localdomain
#ufshost = jump.euca.me
ufshost = jump
ufsport = 8773
verify_ssl = no
output = text
region = eucalyptus

--------------------------

The contents of my /etc/hosts file is:

**cat /etc/hosts**
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
192.168.0.116   jump ec2.jump jump.euca.me ec2.jump.euca.me

--------------------------

I have a working Eucalyptus installation on the server named "jump" and can log into the console with the url **https://jump** as expected and list instances, etc....

--------------------------

The output of the eucalyptus-awscli-plugin installation was reported as successful:

pip3 install --upgrade --no-deps --force-reinstall --user git+https://github.com/corymbia/eucalyptus-awscli-plugin.git
Collecting git+https://github.com/corymbia/eucalyptus-awscli-plugin.git
  Cloning https://github.com/corymbia/eucalyptus-awscli-plugin.git to /tmp/pip-0mlyv_u3-build
Installing collected packages: awscli-plugin-eucalyptus
  Running setup.py install for awscli-plugin-eucalyptus ... done
Successfully installed awscli-plugin-eucalyptus-0.2

--------------------------

The debug output of the failed awscli command is as follows:

aws ec2 describe-regions --debug
2020-07-10 11:42:08,159 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.28 Python/2.7.5 Linux/3.10.0-1127.13.1.el7.x86_64 botocore/1.8.35
2020-07-10 11:42:08,159 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'describe-regions', '--debug']
2020-07-10 11:42:08,160 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fdf8a7f29b0>
2020-07-10 11:42:08,160 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,160 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fdf863def50>
2020-07-10 11:42:08,160 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,160 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2020-07-10 11:42:08,161 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2020-07-10 11:42:08,161 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,161 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2020-07-10 11:42:08,161 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,161 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2020-07-10 11:42:08,162 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,163 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fdf858a3e60>
2020-07-10 11:42:08,163 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,163 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,163 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2020-07-10 11:42:08,172 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/fence-agents/bundled/botocore/data/ec2/2016-11-15/service-2.json
2020-07-10 11:42:08,400 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.ec2: calling handler <function register_retries_for_service at 0x7fdf8719c578>
2020-07-10 11:42:08,402 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: ec2
2020-07-10 11:42:08,420 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <functools.partial object at 0x7fdf8a801f70>
2020-07-10 11:42:08,420 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2020-07-10 11:42:08,421 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2020-07-10 11:42:08,421 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x7fdf8a800140>
2020-07-10 11:42:08,427 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/fence-agents/bundled/botocore/data/ec2/2016-11-15/waiters-2.json
2020-07-10 11:42:08,432 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'filters', <awscli.arguments.ListArgument object at 0x7fdf852fdd50>), (u'region-names', <awscli.arguments.ListArgument object at 0x7fdf852fdd90>), (u'dry-run', <awscli.arguments.BooleanArgument object at 0x7fdf852fddd0>), (u'no-dry-run', <awscli.arguments.BooleanArgument object at 0x7fdf852fde10>)])
2020-07-10 11:42:08,432 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function add_streaming_output_arg at 0x7fdf8a7fa578>
2020-07-10 11:42:08,433 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function _rename_arg at 0x7fdf85516668>
2020-07-10 11:42:08,433 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function _rename_arg at 0x7fdf855222a8>
2020-07-10 11:42:08,433 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <functools.partial object at 0x7fdf8552b050>
2020-07-10 11:42:08,434 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function add_cli_input_json at 0x7fdf863e6b18>
2020-07-10 11:42:08,434 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function unify_paging_params at 0x7fdf8a87f578>
2020-07-10 11:42:08,439 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/fence-agents/bundled/botocore/data/ec2/2016-11-15/paginators-1.json
2020-07-10 11:42:08,440 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-regions: calling handler <function add_generate_skeleton at 0x7fdf8a86baa0>
2020-07-10 11:42:08,441 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-regions: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fdf8459e550>>
2020-07-10 11:42:08,441 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-regions: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fdf852fdfd0>>
2020-07-10 11:42:08,442 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.ec2.describe-regions: calling handler <functools.partial object at 0x7fdf845cbf70>
2020-07-10 11:42:08,442 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.filters: calling handler <function uri_param at 0x7fdf86475230>
2020-07-10 11:42:08,443 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.region-names: calling handler <function uri_param at 0x7fdf86475230>
2020-07-10 11:42:08,443 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.dry-run: calling handler <function uri_param at 0x7fdf86475230>
2020-07-10 11:42:08,443 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.cli-input-json: calling handler <function uri_param at 0x7fdf86475230>
2020-07-10 11:42:08,443 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.ec2.describe-regions.generate-cli-skeleton: calling handler <function uri_param at 0x7fdf86475230>
2020-07-10 11:42:08,443 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-regions: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fdf8459e550>>
2020-07-10 11:42:08,443 - MainThread - botocore.hooks - DEBUG - Event calling-command.ec2.describe-regions: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fdf852fdfd0>>
2020-07-10 11:42:08,444 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,444 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,444 - MainThread - botocore.session - DEBUG - Loading variable region from config file with value 'eucalyptus'.
2020-07-10 11:42:08,444 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,444 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2020-07-10 11:42:08,444 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-07-10 11:42:08,444 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-07-10 11:42:08,444 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-07-10 11:42:08,445 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-07-10 11:42:08,446 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/fence-agents/bundled/botocore/data/endpoints.json
2020-07-10 11:42:08,480 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2020-07-10 11:42:08,480 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fdf87217cf8>
2020-07-10 11:42:08,503 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.ec2: calling handler <function add_generate_presigned_url at 0x7fdf871dd1b8>
2020-07-10 11:42:08,504 - MainThread - botocore.client - DEBUG - Assuming an endpoint for ec2, eucalyptus: https://ec2.jump:8773
2020-07-10 11:42:08,504 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2020-07-10 11:42:08,510 - MainThread - botocore.endpoint - DEBUG - Setting ec2 timeout as (60, 60)
2020-07-10 11:42:08,511 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: ec2
2020-07-10 11:42:08,512 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.DescribeRegions: calling handler <bound method ParameterAlias.alias_parameter_in_call of <botocore.handlers.ParameterAlias object at 0x7fdf87215bd0>>
2020-07-10 11:42:08,512 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.ec2.DescribeRegions: calling handler <function generate_idempotent_uuid at 0x7fdf87217f50>
2020-07-10 11:42:08,513 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeRegions) (verify_ssl=False) with params: {'body': {'Action': u'DescribeRegions', 'Version': u'2016-11-15'}, 'url': 'https://ec2.jump:8773/', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.14.28 Python/2.7.5 Linux/3.10.0-1127.13.1.el7.x86_64 botocore/1.8.35'}, 'context': {'auth_type': None, 'client_region': 'eucalyptus', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7fdf85000a10>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2020-07-10 11:42:08,513 - MainThread - botocore.hooks - DEBUG - Event request-created.ec2.DescribeRegions: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fdf85000910>>
2020-07-10 11:42:08,513 - MainThread - botocore.hooks - DEBUG - Event choose-signer.ec2.DescribeRegions: calling handler <function set_operation_specific_signer at 0x7fdf87217e60>
2020-07-10 11:42:08,514 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-07-10 11:42:08,514 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:ec2.jump:8773
x-amz-date:20200710T174208Z

content-type;host;x-amz-date
903451d1f3cda66f6ac7101b5810af53eb3ce6b47c5162b0b2238ce9086b6a0d
2020-07-10 11:42:08,514 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200710T174208Z
20200710/eucalyptus/ec2/aws4_request
87b5a2e7c70f52c800acb0224e3f1566544fe234b5f78147918579181223872b
2020-07-10 11:42:08,514 - MainThread - botocore.auth - DEBUG - Signature:
f1d03b0ff10dcfd7494fa5ec589dac63416f97fac65c5516a10982a33b20556e
2020-07-10 11:42:08,522 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2020-07-10 11:42:08,522 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): ec2.jump
2020-07-10 11:42:08,548 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 404 156
2020-07-10 11:42:08,549 - MainThread - botocore.parsers - DEBUG - Response headers: {'date': 'Fri, 10 Jul 2020 17:42:08 GMT', 'content-length': '156', 'content-type': 'text/plain; charset=UTF-8', 'connection': 'close', 'server': 'Eucalyptus/5.0.0'}
2020-07-10 11:42:08,550 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0"?><Response><Errors><Error><Code>404 Not Found</Code><Message>unknown</Message></Error></Errors><RequestID>unknown</RequestID></Response>
2020-07-10 11:42:08,550 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ec2.DescribeRegions: calling handler <botocore.retryhandler.RetryHandler object at 0x7fdf8459e4d0>
2020-07-10 11:42:08,550 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-07-10 11:42:08,570 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 209, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 346, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 518, in __call__
    call_parameters, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 638, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 650, in _make_client_call
    **parameters)
  File "/usr/lib/fence-agents/bundled/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/fence-agents/bundled/botocore/client.py", line 615, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (404 Not Found) when calling the DescribeRegions operation: unknown
2020-07-10 11:42:08,571 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (404 Not Found) when calling the DescribeRegions operation: unknown

**Comment by sjones4** [comment]
It looks like you have installed the plugin with `pip3` (for python 3) but are running the aws cli using python 2:

```
aws ec2 describe-regions --debug
2020-07-10 11:42:08,159 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.14.28 Python/2.7.5 
```
